In [1]:
import pandas as pd
import numpy as np

In [2]:
movie = pd.read_csv('tmdb_5000_movies.csv')

In [3]:
credit = pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movie.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [5]:
credit.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [6]:
Movie = movie.merge(credit,on ='title')

In [7]:
Movie.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [8]:
New_movie = Movie[['title','movie_id','genres','keywords','overview','cast','crew']]

In [9]:
New_movie.head()

,title,movie_id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
New_movie.isnull().sum()

title       0
movie_id    0
genres      0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [11]:
New_movie.dropna(inplace=True)

C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\1969637700.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  New_movie.dropna(inplace=True)

In [12]:
New_movie.duplicated().sum()

0

In [13]:
New_movie['keywords'][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [14]:
import ast

In [15]:
def convert(text):
    L =[]
    for i in ast.literal_eval(text):
        L.append(i['name'])
        
    return L

In [16]:
New_movie['keywords'] = New_movie['keywords'].apply(convert)

C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\1121806708.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  New_movie['keywords'] = New_movie['keywords'].apply(convert)

In [17]:
New_movie.head()

,title,movie_id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
New_movie['genres'] = New_movie['genres'].apply(convert)

C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\1981376418.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  New_movie['genres'] = New_movie['genres'].apply(convert)

In [19]:
New_movie.head()

,title,movie_id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
def converter(text):
    L =[]
    counter = 0
    for i in ast.literal_eval(text):
          if counter <3:
                L.append(i['name'])
                counter+=1
                
    return L

In [21]:
New_movie['cast'] = New_movie['cast'].apply(converter)

C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\2925949764.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  New_movie['cast'] = New_movie['cast'].apply(converter)

In [22]:
New_movie.head()

,title,movie_id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
New_movie['cast'] = New_movie['cast'].apply(lambda x:x[0:3])

C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\423453181.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  New_movie['cast'] = New_movie['cast'].apply(lambda x:x[0:3])

In [24]:
def convertor(text):
    L =[]
    for i in ast.literal_eval(text):
         if i['job'] == 'Director':
                L.append(i['name'])
                
    return L

In [25]:
New_movie['crew'] = New_movie['crew'].apply(convertor)

C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\3729814805.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  New_movie['crew'] = New_movie['crew'].apply(convertor)

In [26]:
New_movie.head()

,title,movie_id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,Pirates of the Caribbean: At World's End,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,Spectre,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,The Dark Knight Rises,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,John Carter,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [27]:
# Make string into List
New_movie['overview'].apply(lambda x :x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [28]:
New_movie.head()

,title,movie_id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,Pirates of the Caribbean: At World's End,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,Spectre,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,The Dark Knight Rises,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,John Carter,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [29]:
 New_movie['genres'] = New_movie['genres'].apply(lambda x:[i.replace(" ","") for i in x])

C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\4008758425.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  New_movie['genres'] = New_movie['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [30]:
New_movie['cast'] = New_movie['cast'].apply(lambda x:[i.replace(" ","") for i in x])
New_movie['crew'] = New_movie['crew'].apply(lambda x:[i.replace(" ","") for i in x])
New_movie['keywords'] = New_movie['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\4097740252.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  New_movie['cast'] = New_movie['cast'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\4097740252.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  New_movie['crew'] = New_movie['crew'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\4097740252.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  New_movie['keywords'] = New_movie['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [31]:
New_movie.head()

,title,movie_id,genres,keywords,overview,cast,crew
0,Avatar,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","In the 22nd century, a paraplegic Marine is di...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,Pirates of the Caribbean: At World's End,285,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","Captain Barbossa, long believed to be dead, ha...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,Spectre,206647,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",A cryptic message from Bond’s past sends him o...,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,The Dark Knight Rises,49026,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",Following the death of District Attorney Harve...,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,John Carter,49529,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","John Carter is a war-weary, former military ca...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [32]:
New_movie['Tags'] = New_movie['cast'] + New_movie['crew'] + New_movie['keywords'] + New_movie['genres']

C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\2804121224.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  New_movie['Tags'] = New_movie['cast'] + New_movie['crew'] + New_movie['keywords'] + New_movie['genres']

In [33]:
New_movie.head()

,title,movie_id,genres,keywords,overview,cast,crew,Tags
0,Avatar,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","In the 22nd century, a paraplegic Marine is di...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[SamWorthington, ZoeSaldana, SigourneyWeaver, ..."
1,Pirates of the Caribbean: At World's End,285,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","Captain Barbossa, long believed to be dead, ha...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[JohnnyDepp, OrlandoBloom, KeiraKnightley, Gor..."
2,Spectre,206647,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",A cryptic message from Bond’s past sends him o...,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[DanielCraig, ChristophWaltz, LéaSeydoux, SamM..."
3,The Dark Knight Rises,49026,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",Following the death of District Attorney Harve...,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[ChristianBale, MichaelCaine, GaryOldman, Chri..."
4,John Carter,49529,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","John Carter is a war-weary, former military ca...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[TaylorKitsch, LynnCollins, SamanthaMorton, An..."

In [34]:
Final = New_movie[['movie_id','title','Tags']]

In [35]:
Final.head()

,movie_id,title,Tags
0,19995,Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver, ..."
1,285,Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley, Gor..."
2,206647,Spectre,"[DanielCraig, ChristophWaltz, LéaSeydoux, SamM..."
3,49026,The Dark Knight Rises,"[ChristianBale, MichaelCaine, GaryOldman, Chri..."
4,49529,John Carter,"[TaylorKitsch, LynnCollins, SamanthaMorton, An..."

In [36]:
 Final['Tags'] = Final['Tags'].apply(lambda x:" ".join(x))

C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\874206049.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final['Tags'] = Final['Tags'].apply(lambda x:" ".join(x))

In [37]:
Final['Tags'][0]

'SamWorthington ZoeSaldana SigourneyWeaver JamesCameron cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d Action Adventure Fantasy ScienceFiction'

In [38]:
 Final['Tags'] = Final['Tags'].apply(lambda x:x.lower())

C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\2772789105.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final['Tags'] = Final['Tags'].apply(lambda x:x.lower())

In [39]:
Final.head()

,movie_id,title,Tags
0,19995,Avatar,samworthington zoesaldana sigourneyweaver jame...
1,285,Pirates of the Caribbean: At World's End,johnnydepp orlandobloom keiraknightley gorever...
2,206647,Spectre,danielcraig christophwaltz léaseydoux sammende...
3,49026,The Dark Knight Rises,christianbale michaelcaine garyoldman christop...
4,49529,John Carter,taylorkitsch lynncollins samanthamorton andrew...

In [40]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\sachin\anaconda3\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\sachin\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: joblib in c:\users\sachin\anaconda3\lib\site-packages (from nltk) (1.1.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\sachin\anaconda3\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: tqdm in c:\users\sachin\anaconda3\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in c:\users\sachin\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [41]:
from nltk.stem.porter import PorterStemmer
PS = PorterStemmer()

In [42]:
def stem(text):
    y =[]
    for i in text.split():
        y.append(PS.stem(i))
    return " ".join(y)

In [43]:
Final['Tags'] =Final['Tags'].apply(stem)

C:\Users\Sachin\AppData\Local\Temp\ipykernel_11924\267657969.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Final['Tags'] =Final['Tags'].apply(stem)

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
CV = CountVectorizer(max_features =4000,stop_words='english')

In [45]:
 Vector = CV.fit_transform(Final['Tags']).toarray()

In [46]:
Vector[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [47]:
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
 simi_matrix = cosine_similarity(Vector)

In [49]:
# Index position chnage when sorting so apply enumerate
enumerate(simi_matrix[0])

In [50]:
# Convert into list
list(enumerate(simi_matrix[0]))

[(0, 1.0),
 (1, 0.1254363015010636),
 (2, 0.11826247919781653),
 (3, 0.04003203845127179),
 (4, 0.27735009811261463),
 (5, 0.1283881477532739),
 (6, 0.0),
 (7, 0.19611613513818404),
 (8, 0.10878565864408425),
 (9, 0.16317848796612638),
 (10, 0.2025478734167333),
 (11, 0.11322770341445959),
 (12, 0.1315587028960544),
 (13, 0.10482848367219184),
 (14, 0.19026059766179765),
 (15, 0.10127393670836665),
 (16, 0.14269544824634822),
 (17, 0.2508726030021272),
 (18, 0.1773937187967248),
 (19, 0.179968508266339),
 (20, 0.15191090506254998),
 (21, 0.11826247919781653),
 (22, 0.10878565864408425),
 (23, 0.10878565864408425),
 (24, 0.09805806756909202),
 (25, 0.13867504905630731),
 (26, 0.179968508266339),
 (27, 0.15724272550828777),
 (28, 0.17118419700436519),
 (29, 0.10127393670836665),
 (30, 0.14269544824634822),
 (31, 0.19611613513818404),
 (32, 0.2025478734167333),
 (33, 0.16317848796612638),
 (34, 0.0),
 (35, 0.14708710135363803),
 (36, 0.2175713172881685),
 (37, 0.15191090506254998),
 (38, 0.16984155512168939),
 (39, 0.15724272550828777),
 (40, 0.04902903378454601),
 (41, 0.24514516892273006),
 (42, 0.0),
 (43, 0.1315587028960544),
 (44, 0.062017367294604234),
 (45, 0.11322770341445959),
 (46, 0.19611613513818404),
 (47, 0.4050957468334665),
 (48, 0.1386750490563073),
 (49, 0.11826247919781653),
 (50, 0.23652495839563306),
 (51, 0.2096569673443837),
 (52, 0.19026059766179765),
 (53, 0.0899842541331695),
 (54, 0.054392829322042126),
 (55, 0.17541160386140586),
 (56, 0.18605210188381271),
 (57, 0.0),
 (58, 0.06537204504606134),
 (59, 0.16317848796612638),
 (60, 0.0),
 (61, 0.32635697593225277),
 (62, 0.13074409009212268),
 (63, 0.14708710135363803),
 (64, 0.050636968354183326),
 (65, 0.04003203845127179),
 (66, 0.059131239598908265),
 (67, 0.16984155512168939),
 (68, 0.15191090506254998),
 (69, 0.09245003270420488),
 (70, 0.16317848796612638),
 (71, 0.22237479499833035),
 (72, 0.19611613513818404),
 (73, 0.04756514941544941),
 (74, 0.2175713172881685),
 (75, 0.12403473458920847),
 (76, 0.1283881477532739),
 (77, 0.04756514941544941),
 (78, 0.08770580193070293),
 (79, 0.15724272550828777),
 (80, 0.09805806756909202),
 (81, 0.2620712091804796),
 (82, 0.12267912301642962),
 (83, 0.3508232077228117),
 (84, 0.23652495839563306),
 (85, 0.22496063533292376),
 (86, 0.18605210188381271),
 (87, 0.11826247919781653),
 (88, 0.15724272550828777),
 (89, 0.054392829322042126),
 (90, 0.11322770341445959),
 (91, 0.19611613513818402),
 (92, 0.12009611535381537),
 (93, 0.09245003270420488),
 (94, 0.2853908964926965),
 (95, 0.1365577483997838),
 (96, 0.14708710135363803),
 (97, 0.18605210188381271),
 (98, 0.12009611535381537),
 (99, 0.04902903378454601),
 (100, 0.10482848367219184),
 (101, 0.15724272550828777),
 (102, 0.22645540682891918),
 (103, 0.1254363015010636),
 (104, 0.08178608201095308),
 (105, 0.12403473458920847),
 (106, 0.0704469953676347),
 (107, 0.1315587028960544),
 (108, 0.24514516892273006),
 (109, 0.11322770341445959),
 (110, 0.043852900965351466),
 (111, 0.19611613513818404),
 (112, 0.14269544824634822),
 (113, 0.08362420100070908),
 (114, 0.08362420100070908),
 (115, 0.0899842541331695),
 (116, 0.09805806756909202),
 (117, 0.10127393670836665),
 (118, 0.04181210050035454),
 (119, 0.0704469953676347),
 (120, 0.0),
 (121, 0.1773937187967248),
 (122, 0.14708710135363803),
 (123, 0.12251277836633778),
 (124, 0.09245003270420488),
 (125, 0.1386750490563073),
 (126, 0.22645540682891918),
 (127, 0.19026059766179765),
 (128, 0.0),
 (129, 0.19611613513818404),
 (130, 0.059131239598908265),
 (131, 0.20801257358446093),
 (132, 0.16984155512168939),
 (133, 0.04902903378454601),
 (134, 0.10878565864408425),
 (135, 0.0),
 (136, 0.04902903378454601),
 (137, 0.0),
 (138, 0.15191090506254998),
 (139, 0.06537204504606134),
 (140, 0.062017367294604234),
 (141, 0.10878565864408425),
 (142, 0.05241424183609592),
 (143, 0.11322770341445959),
 (144, 0.04003203845127179),
 (145, 0.04499212706658475),
 (146, 0.062017367294604234),
 (147, 0.13074409009212268),
 (148, 0.13074409009212268),
 (149, 0.16357216402190616),
 (150, 0.17118419700436519),
 (151, 0.18490006540840975),
 (152, 0.0899842541331695),
 (153, 0.11322770341445959),
 (154, 0.062017367294604234),
 (155, 0.0),
 (156, 0.07161148740394328),
 (157, 0.1773937187967248),
 (158, 0.18490006540840975),
 (159, 0.10127393670836665),
 (160, 0.17118419700436519),
 (161, 0.054392829322042126),
 (162, 0.06933752452815364),
 (163, 0.09805806756909202),
 (164, 0.12403473458920847),
 (165, 0.07161148740394328),
 (166, 0.18490006540840975),
 (167, 0.1386750490563073),
 (168, 0.2620712091804796),
 (169, 0.17541160386140586),
 (170, 0.12403473458920847),
 (171, 0.08770580193070293),
 (172, 0.2175713172881685),
 (173, 0.062017367294604234),
 (174, 0.15191090506254998),
 (175, 0.10878565864408425),
 (176, 0.04181210050035454),
 (177, 0.0),
 (178, 0.056613851707229795),
 (179, 0.12403473458920847),
 (180, 0.03580574370197164),
 (181, 0.038461538461538464),
 (182, 0.2175713172881685),
 (183, 0.1408939907352694),
 (184, 0.22645540682891918),
 (185, 0.10482848367219184),
 (186, 0.07283570407292297),
 (187, 0.2175713172881685),
 (188, 0.042796049251091296),
 (189, 0.13074409009212268),
 (190, 0.15724272550828777),
 (191, 0.08362420100070908),
 (192, 0.0),
 (193, 0.24019223070763074),
 (194, 0.0),
 (195, 0.1386750490563073),
 (196, 0.08178608201095308),
 (197, 0.09245003270420488),
 (198, 0.10482848367219184),
 (199, 0.1254363015010636),
 (200, 0.09245003270420488),
 (201, 0.0),
 (202, 0.056613851707229795),
 (203, 0.16317848796612638),
 (204, 0.04089304100547654),
 (205, 0.1386750490563073),
 (206, 0.2620712091804796),
 (207, 0.18490006540840975),
 (208, 0.1773937187967248),
 (209, 0.062017367294604234),
 (210, 0.09805806756909202),
 (211, 0.056613851707229795),
 (212, 0.1283881477532739),
 (213, 0.07692307692307693),
 (214, 0.0),
 (215, 0.10741723110591492),
 (216, 0.11322770341445959),
 (217, 0.10482848367219184),
 (218, 0.06933752452815364),
 (219, 0.12403473458920847),
 (220, 0.1773937187967248),
 (221, 0.04902903378454601),
 (222, 0.13074409009212268),
 (223, 0.12403473458920847),
 (224, 0.16984155512168939),
 (225, 0.09805806756909202),
 (226, 0.056613851707229795),
 (227, 0.04902903378454601),
 (228, 0.23652495839563306),
 (229, 0.16317848796612638),
 (230, 0.14708710135363803),
 (231, 0.0),
 (232, 0.19026059766179765),
 (233, 0.16317848796612638),
 (234, 0.08559209850218259),
 (235, 0.10878565864408425),
 (236, 0.054392829322042126),
 (237, 0.12403473458920847),
 (238, 0.20906050250177272),
 (239, 0.11826247919781653),
 (240, 0.08362420100070908),
 (241, 0.1773937187967248),
 (242, 0.15191090506254998),
 (243, 0.1315587028960544),
 (244, 0.11826247919781653),
 (245, 0.08770580193070293),
 (246, 0.042796049251091296),
 (247, 0.0),
 (248, 0.042796049251091296),
 (249, 0.16317848796612638),
 (250, 0.0),
 (251, 0.06537204504606134),
 (252, 0.043852900965351466),
 (253, 0.12403473458920847),
 (254, 0.09513029883089882),
 (255, 0.0),
 (256, 0.11826247919781653),
 (257, 0.13074409009212268),
 (258, 0.056613851707229795),
 (259, 0.11826247919781653),
 (260, 0.27735009811261463),
 (261, 0.03706246583305506),
 (262, 0.12009611535381537),
 (263, 0.11322770341445959),
 (264, 0.0),
 (265, 0.056613851707229795),
 (266, 0.19026059766179765),
 (267, 0.10878565864408425),
 (268, 0.04756514941544941),
 (269, 0.050636968354183326),
 (270, 0.13497638119975425),
 (271, 0.1315587028960544),
 (272, 0.06933752452815364),
 (273, 0.04181210050035454),
 (274, 0.08559209850218259),
 (275, 0.13867504905630731),
 (276, 0.0899842541331695),
 (277, 0.10127393670836665),
 (278, 0.22496063533292376),
 (279, 0.14708710135363803),
 (280, 0.0),
 (281, 0.04089304100547654),
 (282, 0.10482848367219184),
 (283, 0.0),
 (284, 0.054392829322042126),
 (285, 0.056613851707229795),
 (286, 0.03774256780481986),
 (287, 0.04089304100547654),
 (288, 0.0),
 (289, 0.11322770341445959),
 (290, 0.10878565864408425),
 (291, 0.11322770341445959),
 (292, 0.16984155512168939),
 (293, 0.062017367294604234),
 (294, 0.1773937187967248),
 (295, 0.16317848796612638),
 (296, 0.06726727939963124),
 (297, 0.04756514941544941),
 (298, 0.0),
 (299, 0.08362420100070908),
 (300, 0.19026059766179765),
 (301, 0.10127393670836665),
 (302, 0.14824986333222023),
 (303, 0.056613851707229795),
 (304, 0.1860521018838127),
 (305, 0.2044652050273827),
 (306, 0.11826247919781653),
 (307, 0.16984155512168939),
 (308, 0.13074409009212268),
 (309, 0.1386750490563073),
 (310, 0.07844645405527362),
 (311, 0.16317848796612638),
 (312, 0.13074409009212268),
 (313, 0.11322770341445959),
 (314, 0.0),
 (315, 0.19611613513818402),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.12403473458920847),
 (320, 0.062017367294604234),
 (321, 0.0),
 (322, 0.264197974633739),
 (323, 0.08770580193070293),
 (324, 0.062017367294604234),
 (325, 0.06933752452815364),
 (326, 0.10127393670836665),
 (327, 0.04756514941544941),
 (328, 0.0),
 (329, 0.12267912301642962),
 (330, 0.12267912301642962),
 (331, 0.11826247919781653),
 (332, 0.15724272550828777),
 (333, 0.04756514941544941),
 (334, 0.14269544824634822),
 (335, 0.10127393670836665),
 (336, 0.10878565864408425),
 (337, 0.06537204504606134),
 (338, 0.0),
 (339, 0.0899842541331695),
 (340, 0.11826247919781653),
 (341, 0.11826247919781653),
 (342, 0.18490006540840975),
 (343, 0.0),
 (344, 0.08006407690254358),
 (345, 0.06537204504606134),
 (346, 0.0),
 (347, 0.0),
 (348, 0.09805806756909202),
 (349, 0.08559209850218259),
 (350, 0.10878565864408425),
 (351, 0.0),
 (352, 0.054392829322042126),
 (353, 0.05241424183609592),
 (354, 0.0),
 (355, 0.03706246583305506),
 (356, 0.10127393670836665),
 (357, 0.0),
 (358, 0.11322770341445959),
 (359, 0.11322770341445959),
 (360, 0.0),
 (361, 0.05241424183609592),
 (362, 0.19611613513818402),
 (363, 0.12267912301642962),
 (364, 0.054392829322042126),
 (365, 0.04622501635210244),
 (366, 0.11826247919781653),
 (367, 0.0),
 (368, 0.20801257358446093),
 (369, 0.14708710135363803),
 (370, 0.08770580193070293),
 (371, 0.23652495839563306),
 (372, 0.059131239598908265),
 (373, 0.16317848796612638),
 (374, 0.04902903378454601),
 (375, 0.11826247919781653),
 (376, 0.12403473458920847),
 (377, 0.0),
 (378, 0.0),
 (379, 0.1773937187967248),
 (380, 0.043852900965351466),
 (381, 0.16012815380508716),
 (382, 0.0),
 (383, 0.09805806756909202),
 (384, 0.059131239598908265),
 (385, 0.0),
 (386, 0.038461538461538464),
 (387, 0.04756514941544941),
 (388, 0.0),
 (389, 0.1773937187967248),
 (390, 0.04499212706658475),
 (391, 0.10482848367219184),
 (392, 0.07412493166611012),
 (393, 0.0),
 (394, 0.054392829322042126),
 (395, 0.04902903378454601),
 (396, 0.03774256780481986),
 (397, 0.06537204504606134),
 (398, 0.0),
 (399, 0.050636968354183326),
 (400, 0.1773937187967248),
 (401, 0.0),
 (402, 0.10482848367219184),
 (403, 0.14708710135363803),
 (404, 0.059131239598908265),
 (405, 0.05241424183609592),
 (406, 0.0),
 (407, 0.04902903378454601),
 (408, 0.056613851707229795),
 (409, 0.0),
 (410, 0.14269544824634822),
 (411, 0.13074409009212268),
 (412, 0.19611613513818402),
 (413, 0.16984155512168939),
 (414, 0.06933752452815364),
 (415, 0.11118739749916517),
 (416, 0.08770580193070293),
 (417, 0.056613851707229795),
 (418, 0.06537204504606134),
 (419, 0.13867504905630731),
 (420, 0.15191090506254998),
 (421, 0.0),
 (422, 0.11322770341445959),
 (423, 0.04756514941544941),
 (424, 0.08362420100070908),
 (425, 0.08006407690254358),
 (426, 0.16317848796612638),
 (427, 0.0),
 (428, 0.08770580193070293),
 (429, 0.0),
 (430, 0.0),
 (431, 0.042796049251091296),
 (432, 0.09805806756909202),
 (433, 0.054392829322042126),
 (434, 0.0),
 (435, 0.062017367294604234),
 (436, 0.0),
 (437, 0.05241424183609592),
 (438, 0.062017367294604234),
 (439, 0.0),
 (440, 0.059131239598908265),
 (441, 0.054392829322042126),
 (442, 0.07692307692307693),
 (443, 0.11826247919781653),
 (444, 0.0),
 (445, 0.05241424183609592),
 (446, 0.038461538461538464),
 (447, 0.050636968354183326),
 (448, 0.0),
 (449, 0.10878565864408425),
 (450, 0.059131239598908265),
 (451, 0.043852900965351466),
 (452, 0.06933752452815364),
 (453, 0.05241424183609592),
 (454, 0.08178608201095308),
 (455, 0.03706246583305506),
 (456, 0.050636968354183326),
 (457, 0.20801257358446093),
 (458, 0.13074409009212268),
 (459, 0.050636968354183326),
 (460, 0.059131239598908265),
 (461, 0.1386750490563073),
 (462, 0.0),
 (463, 0.08770580193070293),
 (464, 0.0),
 (465, 0.0),
 (466, 0.29649972666444047),
 (467, 0.20801257358446093),
 (468, 0.05241424183609592),
 (469, 0.10127393670836665),
 (470, 0.10878565864408425),
 (471, 0.12403473458920847),
 (472, 0.1773937187967248),
 (473, 0.09805806756909202),
 (474, 0.0),
 (475, 0.10482848367219184),
 (476, 0.13074409009212268),
 (477, 0.0),
 (478, 0.07844645405527362),
 (479, 0.14824986333222023),
 (480, 0.11322770341445959),
 (481, 0.0),
 (482, 0.059131239598908265),
 (483, 0.16984155512168939),
 (484, 0.056613851707229795),
 (485, 0.11826247919781653),
 (486, 0.19611613513818402),
 (487, 0.16984155512168939),
 (488, 0.10127393670836665),
 (489, 0.0),
 (490, 0.24806946917841693),
 (491, 0.16724840200141816),
 (492, 0.11322770341445959),
 (493, 0.050636968354183326),
 (494, 0.0),
 (495, 0.24806946917841693),
 (496, 0.0),
 (497, 0.0),
 (498, 0.07412493166611012),
 (499, 0.0),
 (500, 0.054392829322042126),
 (501, 0.16724840200141816),
 (502, 0.10482848367219184),
 (503, 0.14269544824634822),
 (504, 0.0),
 (505, 0.16984155512168939),
 (506, 0.056613851707229795),
 (507, 0.23782574707724702),
 (508, 0.15724272550828777),
 (509, 0.0),
 (510, 0.1315587028960544),
 (511, 0.16984155512168939),
 (512, 0.056613851707229795),
 (513, 0.11322770341445959),
 (514, 0.10482848367219184),
 (515, 0.059131239598908265),
 (516, 0.04003203845127179),
 (517, 0.0),
 (518, 0.16012815380508716),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.11322770341445959),
 (524, 0.0),
 (525, 0.04756514941544941),
 (526, 0.0),
 (527, 0.0),
 (528, 0.04499212706658475),
 (529, 0.06537204504606134),
 (530, 0.13074409009212268),
 (531, 0.11826247919781653),
 (532, 0.0),
 (533, 0.056613851707229795),
 (534, 0.13074409009212268),
 (535, 0.19611613513818402),
 (536, 0.0899842541331695),
 (537, 0.1386750490563073),
 (538, 0.0),
 (539, 0.2311250817605122),
 (540, 0.12403473458920847),
 (541, 0.16984155512168939),
 (542, 0.09805806756909202),
 (543, 0.18605210188381271),
 (544, 0.10878565864408425),
 (545, 0.050636968354183326),
 (546, 0.11322770341445959),
 (547, 0.14269544824634822),
 (548, 0.0),
 (549, 0.10878565864408425),
 (550, 0.062017367294604234),
 (551, 0.08006407690254358),
 (552, 0.0),
 (553, 0.043852900965351466),
 (554, 0.0),
 (555, 0.13074409009212268),
 (556, 0.05241424183609592),
 (557, 0.06537204504606134),
 (558, 0.0),
 (559, 0.054392829322042126),
 (560, 0.08006407690254358),
 (561, 0.054392829322042126),
 (562, 0.0),
 (563, 0.06537204504606134),
 (564, 0.09805806756909202),
 (565, 0.08559209850218259),
 (566, 0.042796049251091296),
 (567, 0.054392829322042126),
 (568, 0.10482848367219184),
 (569, 0.056613851707229795),
 (570, 0.056613851707229795),
 (571, 0.04181210050035454),
 (572, 0.13867504905630731),
 (573, 0.042796049251091296),
 (574, 0.056613851707229795),
 (575, 0.10878565864408425),
 (576, 0.054392829322042126),
 (577, 0.2175713172881685),
 (578, 0.10482848367219184),
 (579, 0.13867504905630731),
 (580, 0.06933752452815364),
 (581, 0.1773937187967248),
 (582, 0.21398024625545647),
 (583, 0.08770580193070293),
 (584, 0.06537204504606134),
 (585, 0.0),
 (586, 0.056613851707229795),
 (587, 0.179968508266339),
 (588, 0.0),
 (589, 0.1773937187967248),
 (590, 0.056613851707229795),
 (591, 0.14269544824634822),
 (592, 0.04622501635210244),
 (593, 0.0),
 (594, 0.07412493166611012),
 (595, 0.12403473458920847),
 (596, 0.09805806756909202),
 (597, 0.11322770341445959),
 (598, 0.056613851707229795),
 (599, 0.04756514941544941),
 (600, 0.14824986333222023),
 (601, 0.11826247919781653),
 (602, 0.13074409009212268),
 (603, 0.0),
 (604, 0.12403473458920847),
 (605, 0.0),
 (606, 0.0),
 (607, 0.16317848796612638),
 (608, 0.0),
 (609, 0.10878565864408425),
 (610, 0.16012815380508716),
 (611, 0.059131239598908265),
 (612, 0.16317848796612638),
 (613, 0.06537204504606134),
 (614, 0.04181210050035454),
 (615, 0.06537204504606134),
 (616, 0.0),
 (617, 0.042796049251091296),
 (618, 0.16012815380508716),
 (619, 0.0),
 (620, 0.0),
 (621, 0.10482848367219184),
 (622, 0.05241424183609592),
 (623, 0.0),
 (624, 0.16984155512168939),
 (625, 0.04003203845127179),
 (626, 0.04622501635210244),
 (627, 0.1773937187967248),
 (628, 0.0),
 (629, 0.12403473458920847),
 (630, 0.062017367294604234),
 (631, 0.04499212706658475),
 (632, 0.06537204504606134),
 (633, 0.0),
 (634, 0.08178608201095308),
 (635, 0.04622501635210244),
 (636, 0.05241424183609592),
 (637, 0.04181210050035454),
 (638, 0.08006407690254358),
 (639, 0.0),
 (640, 0.10878565864408425),
 (641, 0.0),
 (642, 0.0),
 (643, 0.16317848796612638),
 (644, 0.09805806756909202),
 (645, 0.08362420100070908),
 (646, 0.056613851707229795),
 (647, 0.04622501635210244),
 (648, 0.08006407690254358),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.05241424183609592),
 (653, 0.12403473458920847),
 (654, 0.17541160386140586),
 (655, 0.062017367294604234),
 (656, 0.0),
 (657, 0.0899842541331695),
 (658, 0.09513029883089882),
 (659, 0.04622501635210244),
 (660, 0.16317848796612638),
 (661, 0.2531848417709166),
 (662, 0.0),
 (663, 0.0),
 (664, 0.13074409009212268),
 (665, 0.16317848796612638),
 (666, 0.09513029883089882),
 (667, 0.0),
 (668, 0.1386750490563073),
 (669, 0.04756514941544941),
 (670, 0.054392829322042126),
 (671, 0.10127393670836665),
 (672, 0.04622501635210244),
 (673, 0.04089304100547654),
 (674, 0.13074409009212268),
 (675, 0.10878565864408425),
 (676, 0.056613851707229795),
 (677, 0.03522349768381735),
 (678, 0.16012815380508716),
 (679, 0.0),
 (680, 0.059131239598908265),
 (681, 0.056613851707229795),
 (682, 0.05241424183609592),
 (683, 0.10878565864408425),
 (684, 0.0),
 (685, 0.062017367294604234),
 (686, 0.0),
 (687, 0.11826247919781653),
 (688, 0.04622501635210244),
 (689, 0.0),
 (690, 0.042796049251091296),
 (691, 0.11322770341445959),
 (692, 0.09245003270420488),
 (693, 0.0),
 (694, 0.038461538461538464),
 (695, 0.09513029883089882),
 (696, 0.0),
 (697, 0.0),
 (698, 0.050636968354183326),
 (699, 0.0),
 (700, 0.054392829322042126),
 (701, 0.06933752452815364),
 (702, 0.03706246583305506),
 (703, 0.062017367294604234),
 (704, 0.09245003270420488),
 (705, 0.062017367294604234),
 (706, 0.07412493166611012),
 (707, 0.0),
 (708, 0.04499212706658475),
 (709, 0.0),
 (710, 0.12403473458920847),
 (711, 0.09805806756909202),
 (712, 0.0),
 (713, 0.04089304100547654),
 (714, 0.0),
 (715, 0.20801257358446093),
 (716, 0.08006407690254358),
 (717, 0.0),
 (718, 0.12403473458920847),
 (719, 0.0),
 (720, 0.04902903378454601),
 (721, 0.062017367294604234),
 (722, 0.0),
 (723, 0.062017367294604234),
 (724, 0.050636968354183326),
 (725, 0.0),
 (726, 0.0),
 (727, 0.0),
 (728, 0.15724272550828777),
 (729, 0.0),
 (730, 0.054392829322042126),
 (731, 0.11826247919781653),
 (732, 0.16317848796612638),
 (733, 0.062017367294604234),
 (734, 0.054392829322042126),
 (735, 0.11322770341445959),
 (736, 0.06933752452815364),
 (737, 0.08559209850218259),
 (738, 0.0),
 (739, 0.06933752452815364),
 (740, 0.17541160386140586),
 (741, 0.04902903378454601),
 (742, 0.059131239598908265),
 (743, 0.056613851707229795),
 (744, 0.09805806756909202),
 (745, 0.06537204504606134),
 (746, 0.19611613513818402),
 (747, 0.06537204504606134),
 (748, 0.05241424183609592),
 (749, 0.0),
 (750, 0.04003203845127179),
 (751, 0.07412493166611012),
 (752, 0.11322770341445959),
 (753, 0.06933752452815364),
 (754, 0.19611613513818404),
 (755, 0.13867504905630731),
 (756, 0.04622501635210244),
 (757, 0.059131239598908265),
 (758, 0.0),
 (759, 0.0),
 (760, 0.0),
 (761, 0.062017367294604234),
 (762, 0.04902903378454601),
 (763, 0.0),
 (764, 0.06933752452815364),
 (765, 0.0),
 (766, 0.0),
 (767, 0.0899842541331695),

In [51]:
# Sorted on basis of second movie so use lambda
sorted(list(enumerate(simi_matrix[0])),reverse=True,key = lambda x:x[1])[1:6]

[(47, 0.4050957468334665),
 (83, 0.3508232077228117),
 (2378, 0.3508232077228117),
 (61, 0.32635697593225277),
 (2409, 0.3235751144647171)]

In [52]:
def recommend(movie):
    index = Final[Final['title'] == movie].index[0]
    distances = sorted(list(enumerate(simi_matrix[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(Final.iloc[i[0]].title)

In [53]:
Final[Final['title'] == 'Avatar']

   movie_id   title                                               Tags
0     19995  Avatar  samworthington zoesaldana sigourneyweav jamesc...

In [54]:
Final.iloc[342].title

'Men in Black'

In [55]:
recommend('Men in Black')

Men in Black II
Men in Black 3
Journey to Saturn
The Helix... Loaded
Wild Wild West

In [56]:
import pickle

In [57]:
pickle.dump(Final,open('movie_list.pkl','wb'))

In [59]:
pickle.dump(Final.to_dict(),open('movies.pkl','wb'))

In [60]:
pickle.dump(simi_matrix,open('similarity.pkl','wb'))